name: Cloud Build Desktop App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.100'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install Velopack CLI
      run: dotnet tool install -g vpk

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build and Package Installer
      run: .\build-installer.ps1

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NovaIsland-Installer
        path: Releases\*
